# Generated by Django 4.2.7 on 2023-12-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedClick',
            fields=[
                ('click_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('list_id', models.CharField(max_length=255)),
                ('aff_net', models.CharField(max_length=255)),
                ('dropp', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unsub',
            fields=[
                ('click_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('list_id', models.CharField(max_length=255)),
                ('aff_net', models.CharField(max_length=255)),
                ('dropp', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
